  const { sequelize } = require("../models");
const { QueryTypes } = require('sequelize');

exports.get = async () => {
  const query = `SELECT P.MENU_SCR_NAME  CLM_MENU_NAME, 
       P.MENU_ID PARENT_MENU_ID, 
       A.MENU_ID,
       (SELECT DS_DESC FROM PGIM_DOC_SETUP WHERE DS_CODE = A.MENU_PARAMETER_12) CLM_PRODUCT,
       A.MENU_PARAMETER_12 CLM_DS_CODE,
       (SELECT MIN(DAP_PROD_CODE) FROM PGIM_DOC_APPL_PRODUCT 
        WHERE DAP_DS_CODE = A.MENU_PARAMETER_12) PRODUCT_CODE,
       (SELECT PROD_DESC FROM PGIM_PRODUCT 
        WHERE PROD_CODE = (SELECT MIN(DAP_PROD_CODE) FROM PGIM_DOC_APPL_PRODUCT 
                           WHERE DAP_DS_CODE = A.MENU_PARAMETER_12)) PRODUCT_DESC,
       A.MENU_PARAMETER_15 CLM_DEPT_CODE,
       (SELECT PROD_CLASS_CODE FROM PGIM_PRODUCT 
        WHERE PROD_CODE = (SELECT MIN(DAP_PROD_CODE) FROM PGIM_DOC_APPL_PRODUCT 
                           WHERE DAP_DS_CODE = A.MENU_PARAMETER_12)) CLASS_CODE,
       (SELECT CLASS_DESC FROM PGIM_PRODUCT, PGIM_CLASS 
        WHERE PROD_CODE = (SELECT MIN(DAP_PROD_CODE) FROM PGIM_DOC_APPL_PRODUCT 
                           WHERE DAP_DS_CODE = A.MENU_PARAMETER_12)
        AND   CLASS_CODE = PROD_CLASS_CODE) CLASS_DESC,  
       A.MENU_PARAMETER_13 CLM_TYPE,
       A.MENU_ACTION  CLM_INST_CODE,
       A.MENU_PARAMETER_5  CLM_SETL_INST_CODE 
FROM MENU_MENUS A, MENU_MENUS P
WHERE A.MENU_PARAMETER_11 = '4' 
AND   A.MENU_ACTION LIKE 'PGIT8000%'
AND   P.MENU_ID = A.MENU_PARENT_ID
AND   UPPER(P.MENU_SCR_NAME) NOT LIKE '%LIFE%'  `;

  const records = await sequelize.query(query, {
    type: QueryTypes.SELECT,
  });

  return records;
};
