const { sequelize, Sequelize } = require("../models");
const { QueryTypes } = Sequelize;

exports.get = async (inst_code) => {
  const query = `  SELECT  IFD_PBF_FLD_NAME AS "COLUMN_NAME",
    MAX(IFD_INST_CODE)KEEP (DENSE_RANK FIRST ORDER BY IFD_SEQ_NO) AS "INSTANCE_CODE",
    MAX(IFD_PROG_CODE)KEEP (DENSE_RANK FIRST ORDER BY IFD_SEQ_NO) AS "PROGRAM_CODE",
    MAX(IFD_PB_BLK_NAME) KEEP (DENSE_RANK FIRST ORDER BY IFD_SEQ_NO) AS "TABLE_NAME",
    MAX(IFD_PROMPT)   KEEP (DENSE_RANK FIRST ORDER BY IFD_SEQ_NO) AS "FIELD_PROMPT",
    MIN(IFD_SEQ_NO)   AS "DISPLAY_ORDER_NO",
    MAX(IFD_MANDATORY_YN_NUM) KEEP (DENSE_RANK FIRST ORDER BY IFD_SEQ_NO) AS "MANDATORY",
    MAX(IFD_DATA_TYPE)KEEP (DENSE_RANK FIRST ORDER BY IFD_SEQ_NO) AS "DATA_TYPE",
    MAX(ifd_form_item_type) KEEP (DENSE_RANK FIRST ORDER BY IFD_SEQ_NO) AS "SOURCE_DESIGN_TYPE",
    MAX(IFD_FLD_LEN)  KEEP (DENSE_RANK FIRST ORDER BY IFD_SEQ_NO) AS "FIELD_LENGTH",
    MAX(IFD_DISP_LEN) KEEP (DENSE_RANK FIRST ORDER BY IFD_SEQ_NO) AS "DISPLAY_LENGTH",
    MAX(IFD_ENTERABLE_YN_NUM) KEEP (DENSE_RANK FIRST ORDER BY IFD_SEQ_NO) AS "ENTERABLE",
    MAX(IFD_UPDATEABLE_YN_NUM) KEEP (DENSE_RANK FIRST ORDER BY IFD_SEQ_NO) AS "UPDATE_YN",
    MAX(IFD_HINT)     KEEP (DENSE_RANK FIRST ORDER BY IFD_SEQ_NO) AS "TOOL_TIP",
    MAX(IFD_HIDE_YN_NUM)     KEEP (DENSE_RANK FIRST ORDER BY IFD_SEQ_NO) AS "HIDE_FIELD_YES",
    MAX(IFD_CANVAS_NAME) KEEP (DENSE_RANK FIRST ORDER BY IFD_SEQ_NO) AS "CANVA_NAME",
      MAX(IFD_TAB_COLUMN) KEEP (DENSE_RANK FIRST ORDER BY IFD_SEQ_NO) AS "TABLE_COLUMN"
  FROM IM_INSTANCE_FIELD_DEFN 
  WHERE IFD_PB_BLK_NAME='PGIT_CLAIM'
    AND IFD_PBF_FLD_NAME NOT LIKE 'M_%'
    AND IFD_PROMPT IS NOT NULL
    AND IFD_CANVAS_NAME='PGIT_CLAIM'
    AND IFD_PROG_CODE='PGIT8000'
   AND IFD_INST_CODE =:inst_code
  GROUP BY IFD_PBF_FLD_NAME  
  ORDER BY "DISPLAY_ORDER_NO";`;

  const records = await sequelize.query(query, {
    type: QueryTypes.SELECT,
    replacements: {
      inst_code
    }
    
  });

  return records;
};