const { sequelize, Sequelize } = require("../models");
const { QueryTypes } = Sequelize;

exports.get = async () => {
  const query = `     SELECT DISTINCT  PFD_FLD_NAME AS "COLUMN_NAME",
      MAX(PFD_PROG_CODE)KEEP (DENSE_RANK FIRST ORDER BY PFD_SEQ_NO) AS "PROGRAM_CODE",
      MAX(PFD_PB_BLK_NAME) KEEP (DENSE_RANK FIRST ORDER BY PFD_SEQ_NO) AS "TABLE_NAME",
      MAX(PFD_PROMPT)   KEEP (DENSE_RANK FIRST ORDER BY PFD_SEQ_NO) AS "FIELD_PROMPT",
      MIN(PFD_SEQ_NO)   AS "DISPLAY_ORDER_NO",
      MAX(PFD_MANDATORY_YN_NUM) KEEP (DENSE_RANK FIRST ORDER BY PFD_SEQ_NO) AS "MANDATORY",
      MAX(PFD_DATA_TYPE)KEEP (DENSE_RANK FIRST ORDER BY PFD_SEQ_NO) AS "DATA_TYPE",
      MAX(Pfd_form_item_type) KEEP (DENSE_RANK FIRST ORDER BY PFD_SEQ_NO) AS "SOURCE_DESIGN_TYPE",
      MAX(PFD_FLD_LEN)  KEEP (DENSE_RANK FIRST ORDER BY PFD_SEQ_NO) AS "FIELD_LENGTH",
      MAX(PFD_DISP_LEN) KEEP (DENSE_RANK FIRST ORDER BY PFD_SEQ_NO) AS "DISPLAY_LENGTH",
      MAX(PFD_ENTERABLE_YN_NUM) KEEP (DENSE_RANK FIRST ORDER BY PFD_SEQ_NO) AS "ENTERABLE",
      MAX(PFD_UPDATEABLE_YN_NUM) KEEP (DENSE_RANK FIRST ORDER BY PFD_SEQ_NO) AS "UPDATE_YN",
      MAX(PFD_HINT)     KEEP (DENSE_RANK FIRST ORDER BY PFD_SEQ_NO) AS "TOOL_TIP",
      MAX(PFD_HIDE_YN_NUM)     KEEP (DENSE_RANK FIRST ORDER BY PFD_SEQ_NO) AS "HIDE_FIELD_YES",
      MAX(PFD_CANVAS_NAME) KEEP (DENSE_RANK FIRST ORDER BY PFD_SEQ_NO) AS "CANVA_NAME",
      MAX(PFD_TAB_COLUMN) KEEP (DENSE_RANK FIRST ORDER BY PFD_SEQ_NO) AS "TABLE_COLUMN"
    FROM IM_PROG_FIELD_DEFN 
    WHERE PFD_PB_BLK_NAME='PGIT_CLM_EST'
      AND PFD_PROG_CODE='PGIT8000' 
      AND PFD_FLD_NAME NOT LIKE 'M_%'
      GROUP BY PFD_FLD_NAME 
    ORDER BY "DISPLAY_ORDER_NO";`;

  const records = await sequelize.query(query, {
    type: QueryTypes.SELECT,
  });

  return records;
};